name: "Stupid Simple Merge"
description: "Does exactly what it says on the tin"
branding:
  icon: 'git-merge'
  color: 'red'
inputs:
  source:
    description: "Source branch to merge from"
    required: true
  target:
    description: "Target branch to merge into"
    required: true
  commit_message:
    description: "Commit message (defaults to '🤖 Automatic Merge - source -> target')"
    required: false
  github_token:
    description: "GitHub token"
    required: true
outputs:
  status: # output will be available to future steps
    description: "One of 'success', 'warning', 'failure' and, 'error'"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}